"""Parameter descriptor schema (MainApp.exe descriptor table) -- loader, value codec, validator.

``schema.json`` next to this module is generated by ``tools/gen_param_schema.py``
from the static descriptor arrays of MainApp.exe v0.0.0.52 (01 §0.2, 02 §2.2).
It carries all 1 001 *bound* descriptors (records whose value pointer targets the
global settings object, the ones persisted in the XML files) plus 147 *unbound*
descriptors (value pointer 0; controller-side ZF/process pages that are never
written to XML).

Each bound descriptor gives: owning table, section, ``Element.Attribute`` key,
``Lang/lang.txt`` label id, type code, default text, unit, min/max, enum option
label ids, a tag string and a unit class.

The schema also carries the *file layouts*: which descriptor tables are
registered to which XML file, in which order. The element/attribute order of a
file is the first-occurrence order of the descriptors (EVIDENCE: this rule
reproduces ``BkHardPara.xml``, ``BkManuPara.xml``, ``BkLayerPara.xml`` and
``1390backup.xml`` exactly -- see the generator docstring for the VAs).

The loader never touches the vendor package; it reads only ``schema.json``.
"""

from __future__ import annotations

import json
import math
import re
from collections.abc import Iterator
from dataclasses import dataclass, field
from enum import IntEnum
from functools import cache
from importlib import resources
from typing import Any, Literal

__all__ = [
    "Descriptor",
    "ElementLayout",
    "GroupLayout",
    "Layout",
    "Schema",
    "SchemaError",
    "Storage",
    "TypeCode",
    "Value",
    "format_double",
    "load_schema",
]

Value = int | float | str
Storage = Literal["int", "double", "string"]


class SchemaError(Exception):
    """Raised for an unknown section/key/layout or a malformed schema file."""


class TypeCode(IntEnum):
    """Descriptor type codes (``R+0x58``).

    Names are INFERENCE [likely] from value ranges and the widgets they drive
    (01 §0.2); the serialisation class of each code is EVIDENCE (every value of
    65 vendor XML files re-formats identically, see ``storage``).
    """

    INT = 1
    DOUBLE = 2
    STRING = 3
    ENUM = 4
    BOOL = 5
    DO_PORT = 6
    DI_PORT = 7
    IPV4_INT = 8
    PULSE_EQUIVALENT = 9
    DA_PORT = 10
    DA_PORT_VALVE = 11
    EXT_DO_PORT = 12
    COM_PORT = 13
    COLORREF = 14


_DOUBLE_TYPES = frozenset({TypeCode.DOUBLE, TypeCode.PULSE_EQUIVALENT})

# C-runtime style numeric prefixes (wcstod / _wtoi accept a leading numeric prefix).
_FLOAT_PREFIX = re.compile(r"\s*([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)")
_INT_PREFIX = re.compile(r"\s*([+-]?\d+)")
_MSVC_SPECIAL = re.compile(r"\s*([+-]?)1\.#(INF|QNAN|SNAN|IND)", re.IGNORECASE)

# What ``boost::lexical_cast<double, wstring>`` (ParaModule ``0x1000d2c0``) accepts.
# The stream step (``0x1000bdc0``) runs a ``num_get`` extraction with ``skipws``
# cleared and then demands WEOF (``cmp ax, 0xffff`` at ``0x1000bee3``), so the whole
# text must be one C++ float literal: no leading or trailing space, no ``_`` digit
# separator, no trailing ``e``/``E``/``+``/``-`` (checked again at ``0x1000d33b``).
_CPP_DOUBLE = re.compile(r"[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?")
_CPP_INT = re.compile(r"[+-]?\d+")
# ``parse_inf_nan_impl`` (``0x1000af70``): an optional sign, then the *whole* rest
# spelled ``nan`` / ``inf`` / ``infinity`` case-insensitively (the constants at
# 0x1001af24/0x1001af48 are L"nan"/L"NAN" and at 0x1001af2c/0x1001af50
# L"infinity"/L"INFINITY"; the 3-char branch is taken only when exactly 3 remain,
# the 8-char branch only when exactly 8 remain), or ``nan(...)``.
_CPP_INF_NAN = re.compile(r"[+-]?(?:nan(?:\(.*\))?|inf(?:inity)?)\Z", re.IGNORECASE)


def format_double(value: float) -> str:
    """Format a double the way the vendor writer does (02 §2.1).

    EVIDENCE: ``0.59999999999999998``, ``11.000000000000002``, ``3`` in the
    vendor files; ParaModule.dll carries the format string ``%.*g``.

    Non-finite values go through ``boost::lexical_cast``'s ``put_inf_nan``
    (``0x1000ade0``), which copies **3** wide characters from ``L"nan"``
    (``0x1001af24``) or ``L"infinity"`` (``0x1001af2c``) after an optional
    ``-``, before the ``swprintf("%.*g", 17)`` at ``0x1000ed37`` is reached.
    So the spellings are ``nan`` / ``-nan`` / ``inf`` / ``-inf`` - not the
    MSVCR100 ``1.#QNAN``/``1.#INF`` this used to write (STATUS X8).

    UNVERIFIED: no sample holds an exponent or a non-finite value. The vendor
    CRT is MSVCR100, whose ``printf`` writes at least three exponent digits
    (``1e-020``); that style is reproduced here.
    """
    if math.isnan(value):
        return "-nan" if math.copysign(1.0, value) < 0 else "nan"
    if math.isinf(value):
        return "-inf" if value < 0 else "inf"
    text = format(value, ".17g")
    if "e" in text:
        mant, exp = text.split("e")
        sign = exp[0]
        text = f"{mant}e{sign}{int(exp[1:]):03d}"  # UNVERIFIED: MSVCR100 3-digit exponent
    return text


def parse_double(text: str) -> tuple[float, bool]:
    """Parse a double; returns ``(value, exact)``.

    ``exact`` is True only for text ``boost::lexical_cast<double>``
    (``0x1000d2c0``) converts without throwing: one whole C++ float literal, or
    a signed ``nan``/``nan(...)``/``inf``/``infinity``.  Python's ``float`` is
    wider than that - it also takes ``1_0``, ``" 5"`` and ``"1.\u00a0"`` - so it
    cannot decide ``exact`` on its own (STATUS X9).

    UNVERIFIED: what the vendor does with the ``bad_lexical_cast`` thrown at
    ``0x1000d366`` for text it rejects.  This keeps returning a value via the C
    ``wcstod`` prefix rule (unparsable text yields 0.0 like ``_wtof``) and flags
    it ``exact=False``, which ``io.params`` reports as *coerced*.
    """
    if _CPP_DOUBLE.fullmatch(text):
        return float(text), True
    if _CPP_INF_NAN.fullmatch(text):
        sign = -1.0 if text[:1] == "-" else 1.0
        body = text.lstrip("+-").lower()
        return (math.copysign(math.nan, sign) if body.startswith("nan") else sign * math.inf), True
    m = _MSVC_SPECIAL.match(text)
    if m:
        kind = m.group(2).upper()
        val = math.inf if kind == "INF" else math.nan
        return (-val if m.group(1) == "-" else val), False
    m = _FLOAT_PREFIX.match(text)
    return (float(m.group(1)) if m else 0.0), False


def parse_int(text: str) -> tuple[int, bool]:
    """Parse an integer; returns ``(value, exact)``.

    ``exact`` uses the same whole-text rule as :func:`parse_double`: ``_wtoi``
    and ``boost::lexical_cast<int>`` both read a plain signed decimal and nothing
    else, while Python's ``int`` also takes ``1_0`` and surrounding whitespace.
    Non-exact text falls back to the C ``_wtoi`` prefix rule (UNVERIFIED).
    """
    if _CPP_INT.fullmatch(text):
        return int(text, 10), True
    m = _INT_PREFIX.match(text)
    return (int(m.group(1)) if m else 0), False


@dataclass(frozen=True, slots=True)
class Descriptor:
    """One parameter descriptor record (0xd0 bytes in MainApp.exe, 01 §0.2)."""

    index: int
    table: str
    va: int
    init_va: int
    section: str
    element: str
    attribute: str
    label_id: str
    type_code: int
    default_text: str
    unit: str
    min: float
    max: float
    enum_ids: tuple[str, ...] | None
    tag: str
    unit_class: int
    value_offset: int

    @property
    def key(self) -> str:
        """``Element.Attribute`` exactly as in the descriptor (e.g. ``SOP.RemoteType``)."""
        return f"{self.element}.{self.attribute}"

    @property
    def type_name(self) -> str:
        """Readable type name (INFERENCE, 01 §0.2)."""
        try:
            return TypeCode(self.type_code).name.lower()
        except ValueError:
            return f"type{self.type_code}"

    @property
    def storage(self) -> Storage:
        """Serialisation class: ``double`` for codes 2/9, ``string`` for 3, else ``int``."""
        if self.type_code in _DOUBLE_TYPES:
            return "double"
        if self.type_code == TypeCode.STRING:
            return "string"
        return "int"

    def parse(self, text: str) -> tuple[Value, bool]:
        """Decode attribute text to a Python value; returns ``(value, exact)``."""
        match self.storage:
            case "double":
                return parse_double(text)
            case "int":
                return parse_int(text)
            case _:
                return text, True

    def format(self, value: Value) -> str:
        """Encode a value as attribute text (%d ints, %.17g doubles, raw strings; 02 §2.1)."""
        match self.storage:
            case "double":
                return format_double(float(value))
            case "int":
                if isinstance(value, float):
                    value = int(value)  # C truncation toward zero
                return str(int(value))
            case _:
                return str(value)

    @property
    def default(self) -> Value:
        """Default value decoded from the descriptor's default text.

        The default text is used as-is for strings (including the vendor's literal
        ``L""`` defaults of ``MSC.LatestFilePath``/``MSC.TestPersonID``).
        ``DO.CurrentAdjGasType`` has an empty default text and decodes to 0
        (UNVERIFIED: C ``_wtoi("")`` semantics assumed).
        """
        return self.parse(self.default_text)[0]

    @property
    def has_range(self) -> bool:
        """True when min/max describe a usable range (``max > min``).

        Several descriptors carry ``0/0`` (strings, some enums such as
        ``MAC_n.ZoreType``); those are treated as unbounded.
        """
        return self.max > self.min

    def validate(self, value: Value) -> list[str]:
        """Return human-readable problems with ``value`` (empty list = OK).

        Checks storage type, min/max (when ``has_range``) and, for enums, that
        the index addresses an option label. Vendor data is not guaranteed to
        satisfy these (e.g. ``MP.ExchangePlatformType`` has max 2 but 5 options),
        so callers should warn, not reject.
        """
        problems: list[str] = []
        if self.storage == "string":
            if not isinstance(value, str):
                problems.append(f"{self.key}: expected string, got {type(value).__name__}")
            return problems
        if isinstance(value, bool) or not isinstance(value, int | float):
            problems.append(f"{self.key}: expected number, got {type(value).__name__}")
            return problems
        if self.storage == "int" and isinstance(value, float) and not value.is_integer():
            problems.append(f"{self.key}: expected integer, got {value!r}")
        if self.has_range and not (self.min <= value <= self.max):
            problems.append(f"{self.key}: {value!r} outside [{self.min:g}, {self.max:g}]")
        if self.type_code == TypeCode.ENUM and self.enum_ids:
            if not (0 <= int(value) < len(self.enum_ids)):
                problems.append(f"{self.key}: enum index {value!r} has no option label")
        return problems


@dataclass(frozen=True, slots=True)
class ElementLayout:
    """One leaf element (e.g. ``<SOP .../>``) and its attributes in file order."""

    name: str
    attributes: tuple[Descriptor, ...]

    def attribute(self, name: str) -> Descriptor:
        """Descriptor of attribute ``name``."""
        for d in self.attributes:
            if d.attribute == name:
                return d
        raise SchemaError(f"<{self.name}> has no attribute {name!r}")


@dataclass(frozen=True, slots=True)
class GroupLayout:
    """One group element (``<PSoftParam>``, ``<PLayerParam3>``) and its children."""

    name: str
    section: str
    slot: int | None
    elements: tuple[ElementLayout, ...]

    def element(self, name: str) -> ElementLayout:
        """Child element layout ``name``."""
        for e in self.elements:
            if e.name == name:
                return e
        raise SchemaError(f"<{self.name}> has no element {name!r}")


@dataclass(frozen=True, slots=True)
class Layout:
    """Complete element/attribute order of one XML file kind."""

    kind: str
    groups: tuple[GroupLayout, ...]
    duplicates: tuple[tuple[Descriptor, Descriptor], ...] = field(default=())

    def group(self, name: str) -> GroupLayout:
        """Group layout by element name (e.g. ``PManuParam``)."""
        for g in self.groups:
            if g.name == name:
                return g
        raise SchemaError(f"layout {self.kind!r} has no group {name!r}")

    def iter_attributes(self) -> Iterator[tuple[GroupLayout, ElementLayout, Descriptor]]:
        """Yield ``(group, element, descriptor)`` in file order."""
        for g in self.groups:
            for e in g.elements:
                for d in e.attributes:
                    yield g, e, d

    @property
    def attribute_count(self) -> int:
        """Number of attributes written to a file of this kind."""
        return sum(len(e.attributes) for g in self.groups for e in g.elements)


class Schema:
    """In-memory view of ``schema.json``."""

    def __init__(self, raw: dict[str, Any]) -> None:
        if raw.get("format") != "nexcut.param-schema/1":
            raise SchemaError(f"unsupported schema format {raw.get('format')!r}")
        self.raw = raw
        self.descriptors: tuple[Descriptor, ...] = tuple(
            _descriptor(i, d) for i, d in enumerate(raw["descriptors"])
        )
        self.unbound: tuple[dict[str, Any], ...] = tuple(raw.get("unbound_descriptors", ()))
        self.tables: dict[str, tuple[Descriptor, ...]] = {}
        for d in self.descriptors:
            self.tables.setdefault(d.table, ())
            self.tables[d.table] += (d,)
        self._by_key: dict[tuple[str, str], Descriptor] = {}
        for d in self.descriptors:
            self._by_key.setdefault((d.section, d.key), d)
        self._layouts: dict[str, Layout] = {}

    @property
    def layout_kinds(self) -> tuple[str, ...]:
        """Names of the known file layouts (``hard``, ``manu``, ``layer``, ...)."""
        return tuple(self.raw["layouts"])

    def get(self, section: str, key: str) -> Descriptor:
        """First descriptor for ``(section, "Elem.Attr")``; raises ``SchemaError`` if unknown."""
        try:
            return self._by_key[(section, key)]
        except KeyError:
            raise SchemaError(f"no descriptor for {section}/{key}") from None

    def find(self, section: str, key: str) -> Descriptor | None:
        """Like ``get`` but returns None when unknown."""
        return self._by_key.get((section, key))

    def layout(self, kind: str) -> Layout:
        """Build (and cache) the file layout ``kind``.

        Rule (EVIDENCE, reproduces the vendor files): walk the registered tables in
        order; for layer tables repeat per slot with group name ``P<section><slot>``,
        otherwise the group is ``P<section>``; groups, elements and attributes are
        appended on first occurrence. A second descriptor for an attribute already
        placed is recorded in ``duplicates`` (the vendor engine binds both storage
        locations to one XML attribute; e.g. ``GRP.OffsetType`` 0xb24c/0xb138).
        """
        if kind in self._layouts:
            return self._layouts[kind]
        try:
            spec = self.raw["layouts"][kind]
        except KeyError:
            raise SchemaError(f"unknown layout {kind!r}") from None
        groups: dict[str, tuple[str, int | None, dict[str, dict[str, Descriptor]]]] = {}
        dups: list[tuple[Descriptor, Descriptor]] = []
        for part in spec["parts"]:
            table = self.tables[part["table"]]
            slots_spec = part.get("slots")
            if slots_spec is None:
                slots: list[int | None] = [None]
            elif isinstance(slots_spec, int):
                slots = list(range(1, slots_spec + 1))
            else:
                slots = list(slots_spec)
            for slot in slots:
                for d in table:
                    gname = f"P{d.section}" if slot is None else f"P{d.section}{slot}"
                    _, _, elems = groups.setdefault(gname, (d.section, slot, {}))
                    attrs = elems.setdefault(d.element, {})
                    if d.attribute in attrs:
                        if slot in (None, slots[0]):
                            dups.append((attrs[d.attribute], d))
                    else:
                        attrs[d.attribute] = d
        layout = Layout(
            kind=kind,
            groups=tuple(
                GroupLayout(
                    name=g,
                    section=sec,
                    slot=slot,
                    elements=tuple(
                        ElementLayout(e, tuple(attrs.values())) for e, attrs in elems.items()
                    ),
                )
                for g, (sec, slot, elems) in groups.items()
            ),
            duplicates=tuple(dups),
        )
        self._layouts[kind] = layout
        return layout


def _descriptor(index: int, d: dict[str, Any]) -> Descriptor:
    element, _, attribute = d["key"].partition(".")
    return Descriptor(
        index=index,
        table=d["table"],
        va=int(d["va"], 16),
        init_va=int(d["init"], 16),
        section=d["section"],
        element=element,
        attribute=attribute,
        label_id=d["label"],
        type_code=int(d["type"]),
        default_text=d["default"],
        unit=d["unit"],
        min=float(d["min"]),
        max=float(d["max"]),
        enum_ids=tuple(d["enum"]) if d["enum"] else None,
        tag=d["tag"],
        unit_class=int(d["unit_class"]),
        value_offset=int(d["value_offset"], 16),
    )


@cache
def load_schema() -> Schema:
    """Load the packaged ``schema.json`` (cached)."""
    text = resources.files(__package__).joinpath("schema.json").read_text(encoding="utf-8")
    return Schema(json.loads(text))
